version: '3.8'

services:
  redis:
    image: redis:alpine
    network_mode: "host"
    restart: always

  sidecar:
    build:
      context: ./src/sidecar
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  server:
    build:
      context: ./src/cpp_server
    network_mode: "host"
    depends_on:
      - redis
      - sidecar
    restart: always
